### ISSUE TITLE
Add support for passing a list of Schema.SObjectField instead of a field set

### ISSUE THREAD

**Issue by jongpie** [jongpie/ApexQueryGenerator#20]
Some standard objects don't allow field sets to be created - to give more flexibility, there should be a second constructor for SObjectRepository that accepts List<Schema.SObjectField> as an alternative to passing a field set.

**Comment by jamessimone** [comment]
(clap)

**Comment by jongpie** [comment]
This issue was moved to jongpie/NebulaFramework#5
